/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedEmailsRouteImport } from './routes/_authenticated.emails'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated.exams'
import { Route as AuthenticatedLeadAssignmentRouteImport } from './routes/_authenticated.lead-assignment'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedSeminarsRouteImport } from './routes/_authenticated.seminars'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated.students'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalCounsellorRouteImport } from './routes/portal.counsellor'
import { Route as PortalExamsRouteImport } from './routes/portal.exams'
import { Route as PortalProgressRouteImport } from './routes/portal.progress'
import { Route as PortalSeminarsRouteImport } from './routes/portal.seminars'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailsRoute = AuthenticatedEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadAssignmentRoute =
  AuthenticatedLeadAssignmentRouteImport.update({
    id: '/lead-assignment',
    path: '/lead-assignment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSeminarsRoute = AuthenticatedSeminarsRouteImport.update({
  id: '/seminars',
  path: '/seminars',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCounsellorRoute = PortalCounsellorRouteImport.update({
  id: '/counsellor',
  path: '/counsellor',
  getParentRoute: () => PortalRoute,
} as any)
const PortalExamsRoute = PortalExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProgressRoute = PortalProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSeminarsRoute = PortalSeminarsRouteImport.update({
  id: '/seminars',
  path: '/seminars',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/lead-assignment': typeof AuthenticatedLeadAssignmentRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/seminars': typeof AuthenticatedSeminarsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/portal/counsellor': typeof PortalCounsellorRoute
  '/portal/exams': typeof PortalExamsRoute
  '/portal/progress': typeof PortalProgressRoute
  '/portal/seminars': typeof PortalSeminarsRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/lead-assignment': typeof AuthenticatedLeadAssignmentRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/seminars': typeof AuthenticatedSeminarsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/portal/counsellor': typeof PortalCounsellorRoute
  '/portal/exams': typeof PortalExamsRoute
  '/portal/progress': typeof PortalProgressRoute
  '/portal/seminars': typeof PortalSeminarsRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/emails': typeof AuthenticatedEmailsRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRoute
  '/_authenticated/lead-assignment': typeof AuthenticatedLeadAssignmentRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/seminars': typeof AuthenticatedSeminarsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/portal/counsellor': typeof PortalCounsellorRoute
  '/portal/exams': typeof PortalExamsRoute
  '/portal/progress': typeof PortalProgressRoute
  '/portal/seminars': typeof PortalSeminarsRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/portal'
    | '/dashboard'
    | '/emails'
    | '/exams'
    | '/lead-assignment'
    | '/reports'
    | '/seminars'
    | '/settings'
    | '/students'
    | '/portal/counsellor'
    | '/portal/exams'
    | '/portal/progress'
    | '/portal/seminars'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/emails'
    | '/exams'
    | '/lead-assignment'
    | '/reports'
    | '/seminars'
    | '/settings'
    | '/students'
    | '/portal/counsellor'
    | '/portal/exams'
    | '/portal/progress'
    | '/portal/seminars'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/portal'
    | '/_authenticated/dashboard'
    | '/_authenticated/emails'
    | '/_authenticated/exams'
    | '/_authenticated/lead-assignment'
    | '/_authenticated/reports'
    | '/_authenticated/seminars'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/portal/counsellor'
    | '/portal/exams'
    | '/portal/progress'
    | '/portal/seminars'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/emails': {
      id: '/_authenticated/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AuthenticatedEmailsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lead-assignment': {
      id: '/_authenticated/lead-assignment'
      path: '/lead-assignment'
      fullPath: '/lead-assignment'
      preLoaderRoute: typeof AuthenticatedLeadAssignmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seminars': {
      id: '/_authenticated/seminars'
      path: '/seminars'
      fullPath: '/seminars'
      preLoaderRoute: typeof AuthenticatedSeminarsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/counsellor': {
      id: '/portal/counsellor'
      path: '/counsellor'
      fullPath: '/portal/counsellor'
      preLoaderRoute: typeof PortalCounsellorRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/exams': {
      id: '/portal/exams'
      path: '/exams'
      fullPath: '/portal/exams'
      preLoaderRoute: typeof PortalExamsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/progress': {
      id: '/portal/progress'
      path: '/progress'
      fullPath: '/portal/progress'
      preLoaderRoute: typeof PortalProgressRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/seminars': {
      id: '/portal/seminars'
      path: '/seminars'
      fullPath: '/portal/seminars'
      preLoaderRoute: typeof PortalSeminarsRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailsRoute: typeof AuthenticatedEmailsRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRoute
  AuthenticatedLeadAssignmentRoute: typeof AuthenticatedLeadAssignmentRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSeminarsRoute: typeof AuthenticatedSeminarsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailsRoute: AuthenticatedEmailsRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRoute,
  AuthenticatedLeadAssignmentRoute: AuthenticatedLeadAssignmentRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSeminarsRoute: AuthenticatedSeminarsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PortalRouteChildren {
  PortalCounsellorRoute: typeof PortalCounsellorRoute
  PortalExamsRoute: typeof PortalExamsRoute
  PortalProgressRoute: typeof PortalProgressRoute
  PortalSeminarsRoute: typeof PortalSeminarsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalCounsellorRoute: PortalCounsellorRoute,
  PortalExamsRoute: PortalExamsRoute,
  PortalProgressRoute: PortalProgressRoute,
  PortalSeminarsRoute: PortalSeminarsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
